# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQDIUEyKVmsTRH31KWfPXYiWGGBtOfnb
"""

import pandas as pd

baza = {
    "FISH": ["Aliyeva Ra'no", "Valiyev Ali", "Karimova Gulnora", "Abdullayev Shavkat", "Mamatqulova Laylo", "Eshonqulov Botir", "Sodiqova Malika", "Andijon Qiz", "Toshkent O'g'il"],
    "Yoshi": [11, 16, 18, 14, 17, 20, 15, 16, 17],
    "Maktabi": ["2-maktab", "Prezident maktabi", "10-maktab", "5-maktab", "Prezident maktabi", "8-maktab", "11-maktab", "10-maktab", "8-maktab"],
    "Jinsi": ["qiz bola", "o'g'il bola", "qiz bola", "o'g'il bola", "qiz bola", "o'g'il bola", "qiz bola", "qiz bola", "o'g'il bola"],
    "Manzili": ["Farg'ona shaxar", "Marg'ilon shaxar", "Andijon shaxar", "Namangan shaxar", "Buxoro shaxar", "Samarqand shaxar", "Toshkent shaxar", "Andijon shaxar", "Toshkent shaxar"]
}

df = pd.DataFrame(baza)

andijon_qizlar = df[(df["Manzili"] == "Andijon shaxar") & (df["Jinsi"] == "qiz bola") & (df["Yoshi"] > 15)]

namangan_ogil = df[(df["Manzili"] == "Namangan shaxar") & (df["Jinsi"] == "o'g'il bola")]

combined_df = pd.concat([andijon_qizlar, namangan_ogil])

print(combined_df)